// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NacosDeleteConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['NacosDeleteConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function NacosDetectVersion(arg1) {
  return window['go']['main']['App']['NacosDetectVersion'](arg1);
}

export function NacosGetConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['NacosGetConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function NacosHistoryDetail(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NacosHistoryDetail'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function NacosHistoryList(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['NacosHistoryList'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function NacosListConfigs(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['NacosListConfigs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function NacosLogin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NacosLogin'](arg1, arg2, arg3, arg4);
}

export function NacosNamespaces(arg1, arg2, arg3) {
  return window['go']['main']['App']['NacosNamespaces'](arg1, arg2, arg3);
}

export function NacosPublishConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['NacosPublishConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
