// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nacos} from '../models';

export function NacosDeleteConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function NacosDetectVersion(arg1:string):Promise<string>;

export function NacosGetConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function NacosHistoryDetail(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<nacos.HistoryDetail>;

export function NacosHistoryList(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<nacos.HistoryPage>;

export function NacosListConfigs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<nacos.ConfigPage>;

export function NacosLogin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<nacos.LoginResult>;

export function NacosNamespaces(arg1:string,arg2:string,arg3:string):Promise<Array<nacos.Namespace>>;

export function NacosPublishConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;
